import os

# ==========================================
# CONFIGURATION: DoorDash Logistics Use Case
# ==========================================
project_configs = {
    "doordash_logistics": {
        "title": "DoorDash Style: Real-Time Logistics & Delivery Matching",
        "problem_statement": (
            "In food delivery, milliseconds matter. A delay in matching a 'Ready' order "
            "to a nearby driver results in cold food and customer churn. We need a system "
            "that ingests thousands of order events and driver GPS pings to optimize "
            "dispatch in real-time."
        ),
        "requirements": [
            "Ingest 2 distinct streams: Order Events (Placed/Cooking/Ready) and Driver Telemetry (GPS).",
            "Latency: Driver matching must occur within 30 seconds of 'Order Ready'.",
            "Data Integrity: Cannot lose 'Order Placed' events (At-Least-Once delivery).",
            "Scalability: Handle spikes during Dinner Rush (6pm - 8pm)."
        ],
        "pipeline_description": (
            "1. **Producer (`producer.py`)**: Simulates a dual-stream of data:\n"
            "   - *Orders*: {Order ID, Restaurant Loc, Status, Timestamp}\n"
            "   - *Drivers*: {Driver ID, Current GPS, Status (Idle/Busy)}\n"
            "2. **Ingestion**: Kafka Topic `logistics-stream`.\n"
            "3. **Processing (`consumer.py`)**: \n"
            "   - Filters for 'Status: Ready' events.\n"
            "   - Calculates Euclidean distance to nearest 'Idle' driver.\n"
            "4. **Logging**: Uses `utils_logger.py` to track dispatch decisions."
        ),
        "instructions": "python producer.py --mode=delivery_rush"
    }
}

# ==========================================
# LOGIC: README Generator
# ==========================================
def generate_readme(target_path, config):
    """
    Generates a formatted README.md file at the specific target path.
    """
    
    # 1. Ensure the directory exists
    os.makedirs(target_path, exist_ok=True)
    
    file_path = os.path.join(target_path, "README.md")
    
    # 2. Format requirements as a bulleted list
    req_list = "\n".join([f"- {req}" for req in config['requirements']])
    
    # 3. Define Markdown block markers (prevents rendering issues)
    B_BASH = "```bash"
    B_END = "```"
    
    # 4. Construct the README content
    content = f"""
# {config['title']}

## 1. Problem Statement
{config['problem_statement']}

## 2. Requirements & KPIs
{req_list}

## 3. Architecture & Pipeline
{config['pipeline_description']}

---

## 4. Technical Implementation

### File Structure
- `producer.py`: Generates mock orders and driver GPS pings.
- `consumer.py`: The "Dispatch Engine" that processes the stream.
- `utils_logger.py`: Standardized logging for audit trails.
- `.env`: Configuration for Database and Kafka connections.

### How to Run this Demo

**Step 1: Install Dependencies**
{B_BASH}
pip install -r requirements.txt
{B_END}

**Step 2: Start the Dispatch Engine (Consumer)**
Open a terminal and run:
{B_BASH}
python consumer.py
{B_END}
*You will see the consumer waiting for 'Order Ready' events...*

**Step 3: Start the Simulation (Producer)**
Open a second terminal and run:
{B_BASH}
{config['instructions']}
{B_END}

**Step 4: Observe the Logs**
Watch the Consumer terminal. You should see logic similar to:
`[INFO] Order #1024 is READY at [47.6, -122.3]`
`[INFO] Dispatching Driver #55 to Order #1024 (Distance: 0.5 miles)`

---
*Generated by Automation Script | {config['title']} Project*
"""

    # 5. Write the file
    with open(file_path, "w") as f:
        f.write(content.strip())
    
    print(f"✅ README successfully written to:\n   {file_path}")

# ==========================================
# MAIN EXECUTION
# ==========================================
if __name__ == "__main__":
    # TARGET PATH: Exactly where you want the file to go
    target_path = "/workspaces/Taashi_Github/Implementation Code/15_Streaming_Big_Data/01_DoorDash_Logistics"
    
    print(f"Targeting directory: {target_path}\n")
    
    # We pass the config for 'doordash_logistics' specifically
    if "doordash_logistics" in project_configs:
        generate_readme(target_path, project_configs["doordash_logistics"])
    
    print("\nProcess Complete.")