"""
Project Structure Setup Script for GEICO Modernization Demo
Creates the complete folder structure for a dbt project following best practices
with Bronze/Silver/Gold medallion architecture.
"""

import os


def create_structure():
    """
    Create the complete dbt project directory structure.
    
    This function sets up:
    - Bronze/Silver/Gold model directories (medallion architecture)
    - Seeds directory for raw CSV data
    - Tests directory for data quality tests
    - Snapshots directory for slowly changing dimensions
    - Analysis directory for ad-hoc queries
    - Data directory for raw CSV files
    - .gitignore file to exclude generated files from version control
    - Placeholder dbt_project.yml file
    """
    # Base paths
    base_dir = "01_platform_modernization_blueprint"
    dbt_dir = os.path.join(base_dir, "dbt_project")
    data_dir = os.path.join(base_dir, "data")
    
    # Define the dbt folder structure (Standard Best Practice)
    subfolders = [
        # Medallion Architecture: Bronze (raw), Silver (cleaned), Gold (aggregated)
        os.path.join(dbt_dir, "models", "bronze"),
        os.path.join(dbt_dir, "models", "silver"),
        os.path.join(dbt_dir, "models", "gold"),
        
        # Seeds: CSV files to load into the warehouse
        os.path.join(dbt_dir, "seeds"),
        
        # Tests: Data quality and validation tests
        os.path.join(dbt_dir, "tests"),
        
        # Snapshots: Type 2 slowly changing dimension tracking
        os.path.join(dbt_dir, "snapshots"),
        
        # Analysis: Ad-hoc queries and exploratory SQL
        os.path.join(dbt_dir, "analysis"),
        
        # Data: Raw CSV files generated by data generation script
        data_dir
    ]
    
    # Create directories
    print("🚀 Setting up project structure...")
    for folder in subfolders:
        os.makedirs(folder, exist_ok=True)
        print(f"   ✓ Created: {folder}")
    
    # Create .gitignore to keep generated files out of version control
    gitignore_path = os.path.join(base_dir, ".gitignore")
    gitignore_content = """# Data files (generated by scripts)
data/*.csv

# dbt artifacts
logs/
target/
dbt_modules/
dbt_packages/

# Python cache
__pycache__/
*.pyc
*.pyo

# IDE files
.vscode/
.idea/
*.swp
*.swo
"""
    
    with open(gitignore_path, "w") as f:
        f.write(gitignore_content.strip())
    print(f"   ✓ Created: {gitignore_path}")
    
    # Create a placeholder dbt_project.yml if it doesn't exist
    dbt_project_path = os.path.join(dbt_dir, "dbt_project.yml")
    if not os.path.exists(dbt_project_path):
        with open(dbt_project_path, "w") as f:
            f.write("# Placeholder for dbt_project.yml\n")
            f.write("# This will be replaced by the dbt setup script\n")
        print(f"   ✓ Created: {dbt_project_path}")
    else:
        print(f"   ⊘ Skipped: {dbt_project_path} (already exists)")
    
    print("\n✅ Project structure setup complete!")
    print(f"   Base directory: {base_dir}")
    print(f"   Ready for data generation and dbt modeling.")


if __name__ == "__main__":
    create_structure()